# Generated by Django 6.1 on 2026-09-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_due_date_project_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
